# Generated by Django 3.1.6 on 2021-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='media_poster',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
