# Generated by Django 3.1.6 on 2021-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='media_poster',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
