# Generated by Django 3.1.6 on 2021-02-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('owner_id', models.IntegerField()),
                ('owner_username', models.CharField(max_length=200)),
                ('title_id', models.IntegerField()),
                ('title_name', models.CharField(max_length=200)),
                ('title_type', models.CharField(max_length=200)),
                ('title_poster', models.CharField(max_length=200)),
            ],
        ),
    ]
