# Generated by Django 3.1.6 on 2021-02-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='title_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='title_poster',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='title_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
