# Generated by Django 3.1.6 on 2021-02-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=200)),
                ('actor_id', models.IntegerField()),
                ('actor_picture', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
